sendsmaily/smaily-wordpress-plugin

Dockerfile
compose.yaml

Configures mailhog service to use correct hostname out of the box. Now emails sent during development will be routed to mailhog service without any additional config.

dev: Configure mailhog

---

compose.yaml

The plugin name is Smaily and this should reflect in the folder name.

dev: Use smaily as container mount path

---

woocommerce/data-handler.class.php

Use wp specific date function instead of generic date. This unifies code with WordPress standards and uses timezone defined in the webpage settings.

woocommerce: Use wp_date instead of date

---

includes/smaily.class.php
woocommerce/profile-settings.class.php

Profile settings are updated without verifying form nonce. This PR implements nonce verification while updating profiles in administrator view and while updating profiles using WooCommerce public profile page.

Verify nonce during profile update

---

includes/smaily-helper.class.php

WordPress linter shows linting errors that can be ignored. This PR adds ignore comments and reasoning behind the ignore into the codebase.

maint: Ignore false-positive linting errors in smaily-helper class

---

admin/template/smaily-admin.php

Unifies patterns used for echoing out text in smaily-admin.php file. Also drops deprecated get_terms function call signature usage.

Refactor smaily-admin.php to WordPress coding standards

---

includes/smaily-lifecycle.class.php
woocommerce/cart.class.php
woocommerce/cron.class.php

Most of DB related warnings is caused by using direct queries, however direct queries are required as we are accessing a custom table. This PR disables phpcs database related rules where needed.
Abandoned cart creation query is now prepared for execution instead of directly providing the table name value.

Suppress database related phpcs warnings

---

readme.txt
smaily.php

Address problems in readme and smaily.php.
- Limits tags to 5
- Shorten plugin description
- Downgrade stable tag to v 1.0.0
- Use GPL-3 license

Update readme and smaily.php according to WordPress standards

---

.github/workflows/wpcs.yml
smaily.php

Implements an github action to lint code automatically. This aims to further improve code quality by not allowing code with linting errors to be merged.

Add GitHub action to lint code

---

readme.md
readme.txt

Tested up to must be a existing WordPress version number.

chore: Set tested WordPress version to 6.7

---

includes/smaily-lifecycle.class.php
includes/smaily-logger.class.php
woocommerce/cron.class.php
woocommerce/subscriber-synchronization.class.php

The file based implementation for the log storage has a flaw - the plugin folders are deleted when upgraded, so using them to store any data is problematic. Instead of using a file for storage we should use some other solution. One possible solution for this is having a separate table for our logs. This PR implements the database based solution.

logger: Refactor logger to DB based implementation

---

.vscode/settings.json
public/partials/smaily-public-advanced.php
woocommerce/cron.class.php
woocommerce/data-handler.class.php
woocommerce/profile-settings.class.php

This PR fixes a mistakenly added named argument in function call. This was probably caused due to a not intentional double-click on the variable. To mitigate the issue I have set editor inlay hints to be visible only when holding ctrl + alt keys.
As the issue came out with PHPCompatibility rule that has not landed in any of the master versions. I scanned the codebase with the `development` branch of the package. I also fixed issues that came out regarding php 8.1 compatibility.

php-compatibility: Improve compatibility with PHP versions

---

admin/smaily-admin.class.php
admin/template/smaily-admin.php
public/template/smaily-rss-feed.php
woocommerce/data-handler.class.php
woocommerce/rss.class.php

Refactors the RSS generation pattern to allow late escaping of echoed variables. Also refactors RSS related functionality to Smaily_WC\Rss class.

rss: Refactor RSS display logic for late escaping

---

phpcs.xml
readme.txt

Updates the minimum PHP version to v7.0 and the minimum WordPress version to v5.0.

Update WP and PHP minimum supported versions

---

admin/js/admin-widget.js
admin/smaily-admin-settings.class.php
admin/smaily-admin.class.php
cf7/admin.class.php
includes/smaily-api.class.php
includes/smaily-widget.class.php
woocommerce/profile-settings.class.php

Use single implementation of listing autoresponders reducing duplicate code. Fixes also spelling and formatting issues.

Use single implementation for listing autoresponders

---

woocommerce/cron.class.php

Removes the code that always subscribes user with the ID of 1. I think this is leftover of some debugging code.

Stop subscribing user with id 1

---

admin/smaily-admin-sanitizer.class.php

Always enforce the default values that are enabled to never change. There can be occasions where these fields are overridden. Now the fields that are mandatory are always enabled.

maint: Sturdy sync fields sanitize function

---

admin/partials/smaily-admin-page.php
blocks/newsletter-signup/src/render.php
cf7/partials/smaily-cf7-admin.php
phpcs.xml
public/partials/smaily-public-basic.php
woocommerce/profile-settings.class.php

This check is tedious in case of casting request values and most places in code ignore this with inline comment. Dropping the rule instead.

maint: Remove nonce verification recommended check

---

admin/smaily-admin-settings.class.php

Moves checkout subscription checkbox under the customer sync tab. This better aligns with the functionality of the checkout subscribe option.

Move checkout subscribe options under customer sync

---

admin/partials/smaily-admin-woocommerce-abandoned-cart.php
includes/smaily-options.class.php
readme.md
woocommerce/cron.class.php

Unify the `product_image_url` parameter value with Magento integration and use a single image for ease of use.

Use single image and product_image_url parameter

---

admin/smaily-admin-renderer.class.php
admin/smaily-admin-settings.class.php

This optimizes API calls by moving the autoresponder loading to the render method, which is only called when the component is actually rendered.

maint: Fix loading autoresponders on admin pages

---

admin/smaily-admin-settings.class.php
compose.yaml
includes/smaily-options.class.php
readme.md
woocommerce/cron.class.php

Abandoned cart messages were not being delivered due to a bug in the code. The $cart parameter were mistakenly overridden causing the following functions to fail. This has been fixed.
Also this PR also improves formatting of the code and adds documentation to the abandoned cart functionality.

fix: Fix abandoned cart messages not delivered

---

includes/smaily-request.class.php
readme.md

Fixes an issue where tyop in the endpoint used for customer sync was causing the sync to fail.
Also updates readme with customer synchronization overview.

fix: Fix wrong endpoint used in customer sync

---

phpcs.xml
readme.txt

Increasing the minimum supported version to 6.0. This allows to use newer functionalities built into the WP regarding blocks development.

Bump the minimum supported WordPress version to 6.0

---

admin/smaily-admin.class.php

Loading admin tabs after translations allows to render translated texts. The previous approach used the admin class constructor, but this loaded too early in the WP lifecycle.

fix: Load admin tabs after translations

---

compose.yaml

Changes mount folder name to smaily-wp-connect to reflect the correct plugin path.

sandbox: Change mount folder name

---

includes/smaily-lifecycle.class.php
integrations/woocommerce/cron.class.php

The Smaily or WooCommerce plugin uses the same generic `smaily` namespace for defining cron schedules. In order to avoid potential conflicts with the Smaily for WooCommerce plugin we should use a more specific namespace.

Use plugin namespace while defiling cron events

---

admin/partials/smaily-admin-credentials.php

These fields should be filled by the user in order to validate credentials. This allows to stop execution prior to making a request allowing a faster feedback to the user. Also adding an asterisk to the labels to further communicate the requirement.

Make credentials form inputs required

---

integrations/woocommerce/cart.class.php
integrations/woocommerce/cron.class.php
readme.md
readme.txt
smaily-connect.php

Fixes an issue where values were not correctly replaced in sql statements that used numbered formatter strings and not numbered formatted strings. This caused where condition to always target customer id 0 account.

fix: Fixes abandoned cart emails not being sent

---

.github/workflows/lint_and_test.yml

First, initialize the environment and then use composer and npm packages to get the cache directories.

ci: Change order lint and test workflow steps

---

admin/css/smaily-admin.css
admin/smaily-admin-renderer.class.php
includes/smaily-api.class.php
includes/smaily-helper.class.php
readme.md
readme.txt
smaily-connect.php

Improves the rendering of the credentials section header notice by adjusting its styles. Previously, the CSS error class caused the notice to appear under the general admin notices, which was misleading. The notice is now correctly displayed near the related input field (credentials).
Also refines the autoresponder listing query by handling invalid values more consistently. If invalid values are found, they are now treated as if no autoresponders are available.

Improve credential error notices and autoresponder query

---

integrations/woocommerce/rss.class.php
readme.md
readme.txt
smaily-connect.php

The current time format is human readable, but the RSS feed is mainly used to import products into email templates. Using the RFC822 time format without translating the value allows Smaily RSS-parser to correctly parse the dates.

integrations/woocommerce: Use RFC822 time format for created_at field
