- admin/template/smaily-admin.php
- includes/smaily-template.class.php
- includes/smaily-widget.class.php
- public/partials/smaily-public-advanced.php
- public/partials/smaily-public-basic.php
- woocommerce/data-handler.class.php
- woocommerce/profile-settings.class.php
Plugin Check reports multiple cases where output is not escaped. This PR aims to fix those errors by correctly implementing wordpress escaping functions on displayed output.
> dev: Fix unescaped output

- admin/smaily-admin.class.php
Fixes issues in smaily-admin.class.php file regarding WordPress coding standards issues.
> Improve smaily-admin.class according to WordPress coding standards

- cf7/partials/smaily-cf7-admin.php
Refactors the file to use unified patterns for echoing out strings.
> Refactor smaily-cf7-admin.php file to WordPress standards

- cf7/admin.class.php
- cf7/partials/smaily-cf7-admin.php
- includes/smaily-widget.class.php
- includes/smaily.class.php
- public/smaily-public.class.php
- woocommerce/subscriber-synchronization.class.php
Improve security by verifying form nonce fields prior to accessing form data. Ignoring nonce verification requirement where there is no need for it.
> Verify nonce before accessing posted data

- admin/template/smaily-admin.php
- cf7/partials/smaily-cf7-admin.php
- public/partials/smaily-public-advanced.php
- public/partials/smaily-public-basic.php
- public/template/smaily-rss-feed.php
- smaily.php
Adds guards for PHP files when directly querying for files. The guards were added to the files that execute procedural code.
> Fix direct file access

- cf7/admin.class.php
- cf7/service.class.php
- includes/smaily.class.php
Adds a Smaily section under CF7 integrations. This adds another place where users are looking for integrations and their setup.
> cf7: Add Smaily under integrations

- admin/partials/smaily-admin-woocommerce-abandoned-cart.php
- admin/smaily-admin-sanitizer.class.php
Fixes default values for abandoned cart fields not checked.
> Fix mandatory abandoned cart fields not checked

- admin/partials/smaily-admin-page.php
- includes/smaily.class.php
- public/partials/smaily-public-basic.php
- woocommerce/data-handler.class.php
- woocommerce/profile-settings.class.php
- woocommerce/subscriber-synchronization.class.php
Moves nonce validation to sanitize_request_smaily_account_fields to keep sanitization and validation close.
> Refactor WC profile settings class

- admin/partials/smaily-admin-woocommerce-abandoned-cart.php
- admin/partials/smaily-admin-woocommerce-customer-sync.php
- blocks/newsletter-signup/src/render.php
- includes/smaily-helper.class.php
- includes/smaily-options.class.php
- public/partials/smaily-public-basic.php
- readme.md
- woocommerce/cron.class.php
- woocommerce/data-handler.class.php
Unify the values that are synchronized with the plugin. Also documents those values in the readme.
> Unify and document synchronization fields

- woocommerce/cron.class.php
Refactor abandoned cart flow for better readability and separates single large function concerns to smaller functions.
> Refactor abandoned cart cron flow

- compose.yaml
Enables script debugging in sandbox.
>  sandbox: Enable script debug

- blocks/newsletter-signup/package-lock.json
- blocks/newsletter-signup/package.json
- blocks/newsletter-signup/src/block.json
Downgrades API to v2 and scripts to v 27 to support WP6.0.
> blocks/signup: Downgrade API and wp/scripts

- admin/js/smaily-admin.js
- admin/smaily-admin-renderer.class.php
Improve the user experience by adding a copy button for copying the feed URL.
> rss-feed: Add copy button for copying the feed URL

- Dockerfile
- composer.json
- composer.lock
- languages/.gitignore
- languages/smaily-et.po
- languages/smaily.pot
Add Estonian translations.
Add tooling to the sandbox for extracting and converting language files.
> Improve translation pipeline

- admin/partials/smaily-admin-page.php
- admin/smaily-admin-renderer.class.php
- admin/smaily-admin-settings.class.php
- admin/smaily-admin.class.php
- includes/smaily-widget.class.php
- languages/smaily-et.po
- languages/smaily.pot
Improves the user onboarding by adding a tutorial tab to the settings page. This aims to provide first instructions inside the plugin to start setting up the integration.
This PR also adds some general improvements regarding wordings and clarity of other explaining text through the plugin.
> ux: Improve onboarding process

- admin/partials/smaily-admin-credentials.php
- admin/partials/smaily-admin-woocommerce-subscriber-sync.php
- admin/smaily-admin-renderer.class.php
- admin/smaily-admin-sanitizer.class.php
- admin/smaily-admin-settings.class.php
- admin/smaily-admin.class.php
- includes/smaily-lifecycle.class.php
- includes/smaily-options.class.php
- includes/smaily-request.class.php
- includes/smaily.class.php
- languages/smaily-et.po
- languages/smaily.pot
- readme.md
- readme.txt
- woocommerce/cron.class.php
- woocommerce/data-handler.class.php
- woocommerce/profile-settings.class.php
- woocommerce/subscriber-synchronization.class.php
Adds missing translations and improves the copy of the plugin.
Changes Customer semantics to Subscriber where applicable.
> Improve copy and missing translations

- includes/smaily-lifecycle.class.php
Fixes a bug where abandoned cart table was not created because of wrong quotes in SQL-query.
> Fix abandoned cart table not created

- .github/workflows/release.yml
Updates the release workflow to use correct plugin name.
> Update plugin name in release workflow

- .github/workflows/release.yml
Updating release script files with better targeting and reordering exclusions alphabetically.
> ci: Update release script packages files

- blocks/checkout-optin/.eslintrc
- blocks/checkout-optin/package-lock.json
- blocks/checkout-optin/package.json
- blocks/checkout-optin/src/edit.js
Adds WordPress runtime dependencies as dev dependencies for better intellisense. 
Fixes linting and formatting errors.
Adds .eslintrc to ignore woocommerce imports as they are not released but bundled into the woocommerce plugin.
> blocks: Checkout Opt-In lint and format
